### ISSUE TITLE
[FR] Create "Are you sure" dialog before deleting items

### ISSUE THREAD

**Issue by m-terlinde** [dfir-iris/iris-web#106]
**Is your feature request related to a problem? Please describe.**
If I'm in a rush and not thinking straight, I could delete items by accident. 

**Describe the solution you'd like**
Create a pop-up/dialogue, to confirm, that I really want to delete the item.

**Describe alternatives you've considered**
I have not found a real one but "think twice".

**Comment by whikernel** [comment]
Hi @m-terlinde,

This is actually something intentional in current versions. We tried to reduce user interactions as much as possible, because we know it can be annoying when things pop up everywhere and you're in an incident - we'll probably change the big "Success" modal at some point for that matter, probably with something more subtle. 
On the other hand, this can lead to mistake yes. That's why we tried to clearly separate deletion functions (other sides of modals or/and in red). 

If that's not enought, then we can add a dialogue before deletion indeed. Maybe we can make it optional per user in that case. Let us know what you think.

**Comment by m-terlinde** [comment]
Sorry, I forgot to answer :(.

An Option per user would be nice!

I can understand the need for quick deletions, but at least in my cases, I just needed to delete things once or twice.

An alternative could be a "revert button" for 15 seconds or so, but I'm not sure how easy it is to stage deletions and push them later.
But it could be a good compromise.

**Comment by whikernel** [comment]
Indeed the revert could be an option but the deferred deletion server side might introduce some challenges. 

Would a client side revert work ? Basically just adding a small JS pop up appearing for a few seconds and would allow to cancel the deletion order. We would need to see how to handle an immediate page change just after a deletion tho. 

Cheers
