### ISSUE TITLE
[BUG] API call for adding timeline event not populating data

### ISSUE THREAD

**Issue by Stephen-98** [dfir-iris/iris-web#157]
The API call to Add a new timeline event does not populate data into IRIS and gives an error.

This is the data structure given by the API documentation:

"event_title": "Test",
"event_content": "",
"event_raw": "",
"event_source": "",
"event_assets": [
"2212"
],
"event_category_id": 1,
"event_in_summary": true,
"event_in_graph": true,
"event_color": "#6861CE99",
"event_date": "2021-12-12T05:45:46.000",
"event_tags": "",
"event_tz": "+00:00",
"custom_attributes": { },
"cid": 1

I have used Postman, Python and Golang to make the post request and kept getting the same error.

The expected behavior is the data to be pushed through to IRIS with a status code of 200 

The error that is received is a status code 500 "Internal server error: server is overloaded or an application error."

I have done all the other API calls and they have not given any issues. Is this error due to request error or is a bug for this specific post request?

**Comment by whikernel** [comment]
Hi @Stephen-98 

if you can add an event via the UI without any error then the problem is coming from the data within your request. The UI is talking to the same API behind the scene.  

You may find more information in the logs of the application - a 500 will generally produce a stack trace there explaining what went wrong. 

From your example, I'd say it might miss the `"event_iocs": []` field. This however depends on the version of IRIS you are using.  If you have this field in the UI when adding an event, then you'd need to add it in your API call. 

<img width="1189" alt="image" src="https://user-images.githubusercontent.com/74464599/207139714-911a9f32-a308-4f0b-aa1a-351a4aff1fc8.png">

Let me know if it helps. 
Cheers

**Comment by taylorwalton** [comment]
Adding another bug to this topic. Using the `"event_iocs": []` results in a successful request and I see the IoC be added to the event.

![image](https://user-images.githubusercontent.com/111797488/207740036-04177f63-d7b3-490c-983b-d149a8cce565.png)

However, when I select the event itself, I do not see the IoC linked, but it does render within the `Graph`

![image](https://user-images.githubusercontent.com/111797488/207740120-66758cae-dead-4aaa-88f1-514f6402091c.png)

**Comment by whikernel** [comment]
Hi @taylorwalton, 

Thanks! I tested and can't reproduce. The IOC in the event added via the API is added correctly. Behind the scene the UI is doing the exact same request when you add an event.   
Could you please try to add an event with some IOC from the UI and see if you have the same issue? 
If you have the same issue, could you please check the JS console for any errors when you are opening the event?

Note: if you have migrated from v1.4.4 to v.1.4.5 please ensure you refresh the case of your browser as a lot of JS has changed. 

Cheers

**Comment by taylorwalton** [comment]
Hey @whikernel,

Aw yup you were right! Opened in incognito and it loaded fine. Sorry about that! 

Best Regards,
Taylor

**Comment by whikernel** [comment]
No worries, glad to hear it's only that and not a coding bug. 😃
