### ISSUE TITLE
[FR] Sanitize domains and IPs in report

### ISSUE THREAD

**Issue by m-terlinde** [dfir-iris/iris-web#184]
**Is your feature request related to a problem? Please describe.**
When I generate a Word report out of a case, the IOCs are plain exported to the document (screenshot from the current public beta instance):

![image](https://user-images.githubusercontent.com/10097313/215809144-76f3f0c1-0794-4997-8bdb-0bb587987bae.png)

I see, that this is not the best example, because the IP IOC was added with sanitation to that case, which should not be needed.

![image](https://user-images.githubusercontent.com/10097313/215813466-89754f92-9e8c-492a-b107-85825622b820.png)

So they could be transformed to clickable links, either in the Word or in a PDF export of some kind.

**Describe the solution you'd like**
IMHO, domain and ip-* IOCs should be sanitized, like `google[.]com`

**Describe alternatives you've considered**
This was the first time for me using the report function. So I haven't searched for a solution yet.

**Comment by whikernel** [comment]
Hi @m-terlinde 

Instead of doing it automatically we added a `escape_dots` filter in the reporting capabilities (see https://github.com/dfir-iris/iris-web/compare/aee93491e6b7...deb583617314). 
It's then up to the reporter creators to decide whether they want to escape or not.  
To escape certain IOC, the template would look like this: 

```
{% for ioc in iocs %}

  {% if ioc.type_name == 'domain' %}

    {{ ioc.ioc_value| escape_dots }}
  
  {% endif %}

{% endfor %}
```

Which would produce `super[.]evil[.]com` instead of `super.evil.com`.  
What do you think?

**Comment by m-terlinde** [comment]
Works for me, thanks!
