### ISSUE TITLE
[FR] - ability to add new case with template

### ISSUE THREAD

**Issue by sjtrotter** [dfir-iris/iris-web#192]
*Please ensure your feature request is not already on the roadmap or associated with an issue. This can be checked [here](https://github.com/orgs/dfir-iris/projects/1/views/4).*

No similar request exists that I could find.

**Is your feature request related to a problem? Please describe.**

No.

**Describe the solution you'd like**

Similar to #185 -  https://github.com/dfir-iris/iris-web/issues/185
But - instead of just adding task templates, it would be nice to select a case template - where prebuilt tasks could be set up and when you create a case they are automatically created within the case. There could also be an option to add note groups and notes that the team is expected to fill out as well.

**Describe alternatives you've considered**

none.

**Additional context**

Something similar is done in TheHive, where you can upload a (json, i think?) template for new cases.

**Comment by whikernel** [comment]
Hi @sjtrotter 

It's been since a long time on our _internal_ roadmap. The idea would be indeed to be able to describe almost all case objects through a JSON and be able to create templates based on that. Templates that you can select during the case creation. We just did had time to implement it. It will hopefully soon 💯

**Comment by sjtrotter** [comment]
ah nice! definitely will be nice. Thanks!
