### ISSUE TITLE
Does not work on Python 3.11

### ISSUE THREAD

**Issue by legoguy1000** [dfir-iris/iris-web#354]
**Describe the bug**
DFIR-IRIS (2.3.7) will not start on python v3.11. It builds properly but then crashes on start.

It appears eventlet and gunicorn are to blame based on the current versions of dependencies in the requirements.txt file. Even updating gunincorn and eventlet to the latest, there are other issues that still cause it to crash, probably due to deprecated functions or something similar.

https://github.com/eventlet/eventlet/issues/687
https://github.com/eventlet/eventlet/issues/842

**To Reproduce**
1. use a python 3.11 base container image and run the build process.

**Expected behavior**
IT works

**Screenshots**
<img width="688" alt="image" src="https://github.com/dfir-iris/iris-web/assets/13125104/992e3679-d8d9-49f6-a449-9bdaf573e39f">

**Additional context**

**Comment by whikernel** [comment]
Hi @legoguy1000 

Due to all the dependencies, notably the bigger ones like eventlet, sqlalchemy and gunicorn we need to fix the Python version until these dependencies are all working together for a specific version. Python 3.11 is not supported now and you should use the version pushed in the releases.

**Comment by SaadTPTW** [comment]
any news about this ?
