### ISSUE TITLE
WARNING :: post_init :: create_safe_admin :: >>> Administrator already exists

### ISSUE THREAD

**Issue by bret99** [dfir-iris/iris-web#399]
All attempts ended with [docker logs CONTAINER_ID] "WARNING :: post_init :: create_safe_admin :: >>> Administrator already exists"/
Phases:
git clone https://github.com/dfir-iris/iris-web.git
cd iris-web 
git checkout v2.4.5
cp .env.model .env

POSTGRES_USER=postgres
POSTGRES_PASSWORD=postgres
POSTGRES_ADMIN_USER=raptor
POSTGRES_ADMIN_PASSWORD=raptor
IRIS_SECRET_KEY=powerful
IRIS_SECURITY_PASSWORD_SALT=powerful
INTERFACE_HTTPS_PORT=5269

docker-compose build
docker-compose up -d

**Comment by keid2000** [comment]
start it build it from scratch:
docker build --no-cache .

or do it on new VM

**Comment by cybertricks** [comment]
I have done the same for me also same issue.
<img width="850" alt="Screenshot 2024-02-08 at 6 04 54 PM" src="https://github.com/dfir-iris/iris-web/assets/33148205/721868a7-8d5d-4158-943e-30b94d50d358">

**Comment by bret99** [comment]
If Admin already exists then what password?

**Comment by lelondono** [comment]
I encountered the same issue and found a workaround that resolved it for me. Here's a more detailed breakdown of the steps I followed:

- Stop All Running Containers: This ensures that there are no active containers that might be using the resources we need to modify or delete. 

`docker-compose stop
`

- List All Containers: Including the stopped ones helps to identify all containers, ensuring none are missed during cleanup.

`docker ps -a
`

- Remove Related Containers Manually: This step involves deleting the containers in order to enable volume remove. Replace <container_id> with the actual ID of the container you wish to remove. You can find the ID in the list generated by the previous command.
 
`docker container rm <container_id>
`

- List All Docker Volumes: This helps identify all volumes, including those related to Dfir-Iris, that might need to be removed.

`docker volume ls
`

- Remove Dfir-Iris Related Volumes: Be cautious with this step to avoid deleting volumes unintentionally. Replace iris-web_db_data with the actual name of the volume you intend to remove.

`docker volume rm iris-web_db_data
`

- Update the .env File: Modify the .env file to set a manual password or make other necessary configuration changes. This step is crucial for ensuring that the rebuilt containers have the correct settings.
 

- Rebuild Containers Without Cache: This ensures that your containers are built from scratch, using the latest versions of images and incorporating any changes made to the Dockerfile or related configurations. I believe that rebuilding with cache could also be a viable solution.

`docker-compose build --no-cache
`

By following these steps, I was able to work around the issue. Please remember to back up relevant data before removing any containers or volumes to prevent data loss. I hope this helps others facing the same problem!
