### ISSUE TITLE
FR: Icons for custom assets

### ISSUE THREAD

**Issue by m-terlinde** [dfir-iris/iris-web#44]
Hey guys,

first of all let me say "thank you" for your work! I think IRIS will become a great and handy tool and I appreciate the fresh start.

I have a feature request: custom asset types will get an empty icon on the Graph. On the creation of the custom asset type, I want to upload an icon for it.

As a side note: is it on purpose, that the type "Windows - DC" does not have an icon as well?

Thanks once again,
Matthias

**Comment by whikernel** [comment]
Hi @m-terlinde  

Thanks for your kind feedback and the issue! 
So the unknown/custom assets type were indeed missing an icon. This was fixed in https://github.com/dfir-iris/iris-web/commit/e8950f69cc7bd57a562b8c72db9ef25402ea687f and will be commited in the next minor version. There will be an interrogation mark when the asset type is not recongnised. 

Indeed it would be great to be able to upload an image for custom asset types. The way it's working for now is by pattern. For instance if your asset type contains `computer` and also `windows` then the `windows_computer.png` is picked. If the asset is compromised then the red version is chosen. It's really not an ideal system. It will be changed, but probably not in the next minor version. 

 And for the DC, yes indeed, there's an entry for `domain controller` but not `DC`. We'll update it, so at least the default asset types have proper icons !

**Comment by m-terlinde** [comment]
Thanks a lot, sounds good.
The heuristic is better than no icon, so probs for this solution.

**Comment by sebastiandemmer** [comment]
Hi,
I am currently working on an implementation to allow Icon uploads for asset types:
![image](https://user-images.githubusercontent.com/103210921/164081180-0395451b-1944-40a7-b14d-bef043d52342.png)
![image](https://user-images.githubusercontent.com/103210921/164081437-6f293c7c-fc76-4902-aac5-120886dd79f9.png)

I am having trouble creating a multipart/form-data field that passed through the the "api_admin_required" function and passes the form validation. 

I had the alternative idea of putting the icon payload into base64 and transferring them in the JSON payload but I am having trouble with async base64 calculation in JS.

Any ideas on what the cleanest implementation would be? 

BR,
Sebastian

**Comment by whikernel** [comment]
Hi @sebastiandemmer  ! 

Nice, thanks for stepping in for that one. 
For the file upload, you can try to replicate what was done for the reports templates. It should be similar, noth concerning a multipart ending on a API admin endpoint. 

The Python is here : https://github.com/dfir-iris/iris-web/blob/6a422c71afbc8d5bf626cced145ff6e62e7fb73f/source/app/blueprints/manage/manage_templates_routes.py#L98
And the JS bit :
https://github.com/dfir-iris/iris-web/blob/6a422c71afbc8d5bf626cced145ff6e62e7fb73f/source/app/static/assets/js/iris/manage_templates.js#L102 

Let us know if it helps :) 
Cheers

**Comment by sebastiandemmer** [comment]
Hi @whikernel,
thanks for the code references, that was super useful and I have a working version now. 
Could you please help me how to create the alembic db migration file?
Thanks

**Comment by whikernel** [comment]
@sebastiandemmer, nice to hear ! 
For Alembic, you need to fire up a terminal, go to the `source` folder and then from within the virtual env : 
`alembic -c app/alembic.ini revision -m "A few words to describe your changes"` 

This will create a new revision file under `source > app > alembic > versions`. It's a Python file that basically describes what needs to be updated DB-wise. You can take example from the ones we already have generated. 

During your tests you might face the issue that Alembic does not apply your changes after you executed it once. It's because it keeps tracks of the applied revisions in a table `alembic_version`.  It doesn't know you changed the revision file. 
In that case the trick is to connect to the DB, and then delete the entry in the `alembic_version`. If you're using the DB docker this gives: 

1.  `docker exec -it <db_container_id> /bin/sh`
2. `su postgres`
3. `psql`
4. `\c iris_db;`
5. `DELETE FROM alembic_version;`
6. Restart the IRIS web app - your changes should be applied 

Hope it will help you, 
Cheers

**Comment by sebastiandemmer** [comment]
@whikernel thanks, that was very helpful, will send a merge request in a bit.
May be a nice addition to the "Development" section of the docs to include these steps :)

Cheers!
