### ISSUE TITLE
Administrator user password

### ISSUE THREAD

**Issue by shehryartalat** [dfir-iris/iris-web#558]
The dafault user of Administrator with password of MySuperAdminPassword! not working. Reasolve this issue

**Comment by whikernel** [comment]
Hi, 

Kindly check the documentation on how to recover the admin password if you lost it. 

https://docs.dfir-iris.org/latest/operations/access_control/authentication/#changing-a-lost-password

Otherwise you can start from scratch with 
"""
docker compose down -v 
docker compose up 
"""

The admin password will be print out in the logs
