### ISSUE TITLE
[FR] Include user/analyst ID in timeline event export (CSV)

### ISSUE THREAD

**Issue by cudeso** [dfir-iris/iris-web#65]
**Is your feature request related to a problem? Please describe.**
The CSV export of the events in the timeline does not contain the user/analyst who added the event. The data can be found via the activity log but it would be great if this is also included in the export.

**Describe the solution you'd like**
Add "username" to the CSV export in event timeline

**Comment by m-terlinde** [comment]
One note from my side: it would be ideal to make this field optional on a per export basis. In most cases, you will not need track your analysts and to keep it optional helps to keep the GDPR compliance according to data minimisation.

Am 2. Februar 2022 16:41:41 MEZ schrieb Koen Van Impe ***@***.***>:
>**Is your feature request related to a problem? Please describe.**
>The CSV export of the events in the timeline does not contain the user/analyst who added the event. The data can be found via the activity log but it would be great if this is also included in the export.
>
>**Describe the solution you'd like**
>Add "username" to the CSV export in event timeline
>
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/dfir-iris/iris-web/issues/65
>You are receiving this because you are subscribed to this thread.
>
>Message ID: ***@***.***>
-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by cudeso** [comment]
If you work with multiple analysts on one case it's not always directly known who adds a specific event. 
Maybe instead of the username add the **userid** (integer) for compliancy reasons?

**Comment by whikernel** [comment]
For now the timeline export is done locally in JS with the data available in the current view. The user name or user ID are not part of it. 

The event table actually don't have a `created_by` field, there's only the last update information. Which means the only way to trace back who created the event is by looking at the activity history. That's a good point, we'll add this field 👍  

As for the export, we can try to add another button `Download with users identifier` int he dropdown.  
GDPR compliance is actually a good question since the plafeform registers all activities by default to keep an automatic follow up of the investigations...
